// Code generated by ihatit. DO NOT EDIT.
// source: {{ .source }}

package db

import (
    {{ range .imports }}
    {{ .alias }} "{{ .package }}"
    {{ end }}
)

{{ range .models }}
type {{ .Name }} struct {
    {{ range .models }}
    {{ .name }} {{ .type }}
    {{ end }}
}

{{ end }}